[package]
name = "bevy_mod_spritesheet"
description = "Create TextureAtlasLayouts from sprite sheet formats, such as JSON Array, and specify them on components by frame name"
license = "MIT"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.13.1", default-features = false, features = [
    "bevy_asset",
    "bevy_sprite",
] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"

[[example]]
name = "default_loader"

[dev-dependencies]
bevy = "0.13.1"
